extends Stage

onready var _little_girl = $LittleGirl
onready var _dude = $RandomDude
onready var _flying_guardian = $FlyingGuardian
onready var _meet_mr_p = $MeetMrP
onready var _encounter_floating_box = $EncounterFloatingBox
onready var _enter_floaties_area = $EnterFloatiesArea
onready var _meet_angelo = $MeetAngelo
onready var _npc_hideout = $NpcHideout
onready var _anim_player = $AnimationPlayer

var _little_girl_path = "res://Character/LittleGirl.tscn"


func _ready():
#	_player.set_current_state("ON_CUTSCENE")
	_player.set_is_using_sword(true)
	_player.play_animation("Happy")
	_dude.play_animation("Angry")


func _unhandled_key_input(event):
	if event.is_action_pressed("reload"):
		get_tree().reload_current_scene()


func arrived_on_new_area():
	_player.play_animation("Idle")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"Ahh... finally...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Finally~\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Whoa...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player._appearance.scale.x = -1
	_dialog_box.append_text("Kyoko: \"Where are we?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player._appearance.scale.x = 1
	_dialog_box.append_text("Hikari: \"This is where i came from.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("ArrivedOnNewArea2")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Hikari: \"Up ahead is where my manager, Mr. P, live.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Ahh, I see...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("ArrivedOnNewArea3")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Kyoko: \"Let's go now then, your manager must be worry about you know.\"[break].", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.set_global_position(_npc_hideout.get_global_position())
	_player.set_current_state("IDLE")


func _on_MeetMrP_body_entered(body):
	_player.set_current_state("ON_CUTSCENE")
	_player.play_animation("Walk")
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetMrP1")
	yield(_anim_player, "animation_finished")
	_player.play_animation("Idle")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"I'm back!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude._appearance.scale.x = -1
	_dude.play_animation("Shocked")
	_dialog_box.append_text("Mr. P: \"BY GOD!!!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Walk")
	_anim_player.play("MeetMrP2")
	yield(_anim_player, "animation_finished")
	_dude._appearance.scale.x = 1
	_little_girl._appearance.scale.x = -1
	_player._appearance.scale.x = -1
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"Where have you been???\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"...Um...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"You've gone for a few days already.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Do you realize many people are worry about you...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Sad")
	_dialog_box.append_text("Hikari: \"...Sorry...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"..Sigh...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Walk")
	_anim_player.play("MeetMrP3")
	yield(_anim_player, "animation_finished")
	_dude._appearance.scale.x = -1
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"And who are you?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Normal")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"Ah, um, I'm-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl._appearance.scale.x = 1
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"Ah, this is Kyoko. She helpes me to get here.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Hooo. And then, what do you want?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Ah.. Nothing. I just found her by chance.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Well, we really appreciate your help.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"As for you, Hikari.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Go inside and prepare for your concert. We don't have much time left.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"...Okay...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetMrP4")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Mr. P: \"Sigh...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Scared")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"Will the concert be ok?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"I mean, like, does she already prepared for that? She's been missing for a while, right?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"I'm sure you've already know about her first concert, right?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"It's really not an unexpected things, to be honest.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"It was her very first public singing, yet she truly believe in her singing.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"She only did minimun amount of training and preparation.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"She said that everything will be fine. Her singing is already good enough in her opinion.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"And yeah, when the concert happened...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Unfortunately, it was overwhelming for her...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dialog_box.append_text("Mr. P: \"...And the rest is what people know...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Normal")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"...I see...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude._appearance.scale.x = 1
	_dialog_box.append_text("Mr. P: \"She really does love to sing tho.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P.: \"But she procrastinate a lot.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dude._appearance.scale.x = -1
	_dialog_box.append_text("Mr. P: \"...But don't worry about it...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"She've been practicing a lot after that incident.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"So I told her to go find inspiration for the next new song.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"I invited some of her friends, so she can have fun...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"Who thought it will end up like this...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Happy")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: (Ahh... So that's what happened)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Where were you find her anyway?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Ah, you see, I-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("HIKARI: \"MR. P!!!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dude._appearance.scale.x = 1
	_player.play_animation("Normal")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Mr. P: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl._appearance.scale.x = -1
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetMrP5")
	yield(_anim_player, "animation_finished")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"Mr. P, I found this in my mic case...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Shocked")
	yield(_dude._anim_player, "animation_finished")
	_dude.play_animation("Idle")
	_dialog_box.append_text("Mr. P: \"'The mic is mine now. I will never let her do that awful display again.'\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"'-Angelo, Ruler of The Sky\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"Tsk, that bastard.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"What should we do? What should we do?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"I still have things to take care for the concert.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dude._appearance.scale.x = -1
	_dialog_box.append_text("Mr. P: \"...Kyoko, I need your help.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"This guy, Angelo, He lives nearby.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"I need you to go grab that mic back.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Please, we don't have much time..\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Sad")
	_dialog_box.append_text("Hikari: \"...Kyoko, please help...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (Welp, she already did her best this time...)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Happy")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"...I see what can I do.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"YAY~\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude._appearance.scale.x = 1
	_dialog_box.append_text("Mr. P: \"As for you, Hikari, prepare yourself. We will go to the stage soon.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"...I want to go with Kyoko.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.5)
	_dude.play_animation("Angry")
	_dialog_box.append_text("Mr. P: \"Now WHAT ARE YOU TALKING ABOUT?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"I've already done my preparation, and I've practice a lot.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Still, that doen't mean you can-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.25)
	_dialog_box.append_text("Hikari: \"I NEED TO GO!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"...I believe sir Angelo have his reason to do this.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"...I want to talk to him...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"No\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Hikari: \"I MUST GO TALK TO HIM.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (...Good one there, girl...)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"What kind of reasoning is that?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"You'll go with me NOW.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"MR. P\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude._appearance.scale.x = -1
	_dialog_box.append_text("Mr. P: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"I'll go only if she's with me.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"What the-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Normal")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"Mr. P\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"I promised I'll bring her to the stage, safe and sound.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dude.play_animation("Idle")
	_dialog_box.append_text("Mr. P: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Mr. P: \"Don't be late, okay?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Normal")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"You got it.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Hikari, let's go, We don't have much time.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Okay.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player._appearance.scale.x = 1
	_player._camera.zoom.x = 1
	_player._camera.zoom.y = 1
	_player._camera.position.x = 0
	_player._camera.position.y = -16
	body.set_current_state("IDLE")
	_little_girl.set_global_position(_npc_hideout.get_global_position())
	_anim_player.play("GiveGreenBox")
	_meet_mr_p.queue_free()


func _on_EncounterFloatingBox_body_entered(body):
	_player.set_current_state("ON_CUTSCENE")
	_player.play_animation("Idle")
	_player._appearance.scale.x = -1
	_little_girl.play_animation("Idle")
	_little_girl.set_global_position(_encounter_floating_box.get_global_position())
	_little_girl._appearance.scale.x = -1
	_dialog_box.append_text("Kyoko: \"Whoa, what's that?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Ah, remember those red boxes we encountered before?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"This is that, but can float...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"...I see...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"People here sometimes use this to reach places that they can't reach.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (Hmmm, quite useful...)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.set_global_position(_npc_hideout.get_global_position())
	body.set_current_state("IDLE")
	_encounter_floating_box.queue_free()


func _on_EnterFloatiesArea_body_entered(body):
	_player.set_current_state("ON_CUTSCENE")
	_player.play_animation("Walk")
	_little_girl.play_animation("Walk")
	_anim_player.play("EnterFloatiesArea1")
	yield(_anim_player, "animation_finished")
	_player.play_animation("Idle")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Kyoko: \"Now where are we?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Ah, we've finally here.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("EnterFloatiesArea2")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Hikari: \"People said Mr. Angelo lives here.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"A place full with some floating ground\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("EnterFloatiesArea3")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Hikari: \"My friend said that Mr. Angelo live up ahead.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"I see...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("EnterFloatiesArea4")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Kyoko: \"Let's get going then.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Don't worry, we can do it, okay?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Yeah\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Let's go.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.set_current_state("IDLE")
	_player._apppearance.scale.x = 1
	_little_girl._apppearance.scale.x = 1
	_little_girl.set_global_position(_npc_hideout.get_global_position())
	_enter_floaties_area.queue_free()


func _on_MeetAngelo_body_entered(body):
	_player.set_current_state("ON_CUTSCENE")
	_player._anim_player.play("Walk")
	_little_girl._anim_player.play("Walk")
	_anim_player.play("MeetAngelo1")
	yield(_anim_player, "animation_finished")
	_little_girl.play_animation("Shocked")
	_player.play_animation("Scared")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_player.shake_screen(0.3)
	_dialog_box.append_text("???: \"HO HOOO...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("???: \"So you actually come...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_flying_guardian.play_animation("Fly")
	_anim_player.play("MeetAngelo2")
	yield(_anim_player, "animation_finished")
	#Angelo descend
	_dialog_box.append_text("Angelo: \"I, am Angelo\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"No being is higher than ME!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"And downhere, stands a mere human that shameful ran away after realizing her worthlessness...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Now what are you doing here, little princess?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo : \"Are you planning to make an excuse, not coming to your second concert?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"If only you are not under Mr. P protection...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Why a mere Mr. P's minion was send to to accompany this piece of trash?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Does he actually believe that you two are enough to grab this back???\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("MeetAngelo3")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Hikari: \"THE MIC!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_anim_player.play("MeetAngelo4")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Angelo : \"WHO ALLOW YOU TO TAKE THE MIC?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: *gasp*[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: *gasp*[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("HIKARI: \"THAT'S ENOUGH!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Ho ho...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetAngelo5")
	yield(_anim_player, "animation_finished")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"Sir Angelo.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"I come here to sing for you!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"...What!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.25)
	_dialog_box.append_text("Angelo: \"HO HO\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Are you out of your mind?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.25)
	_dialog_box.append_text("Angelo: \"DON'T YOU REALIZE YOUR SINGING IS?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"I've trained myself since that day...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"I'll prove it to you!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Angelo: \"IT'S USELESS!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Hikari: \"NO IT'S NOT!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Hikari, that's dangerous\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: *gasp*[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"Sigh...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (Damn. That was a great performance...)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_flying_guardian.play_animation("Fly")
	_flying_guardian._appearance.scale.x = -1
	_anim_player.play("MeetAngelo6")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Kyoko: \"...What?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"After all that shit he have done,\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.play_animation("Happy")
	yield(_player._anim_player, "animation_finished")
	_player.play_animation("Idle")
	_player.shake_screen(0.3)
	_dialog_box.append_text("Kyoko: \"HE JUST FLEW AWAY, LIKE THAT?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"...what's wrong with this dream...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	# Hikari went to grab the mic
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetAngelo7")
	yield(_anim_player, "animation_finished")
	_little_girl.play_animation("Idle")
	_dialog_box.append_text("Hikari: \"MY MIC!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Phew, finally...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"Now all we need to do is to the stage and-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Kyoko: \"OH CRAP!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl._appearance.scale.x = 1
	_dialog_box.append_text("Hikari: \"Kyoko, what's wrong?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"WE DON'T HAVE MUCH TIME!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: \"...If we travel like before, by the time we reach the stage, it sill be already too late...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Shocked")
	_player.shake_screen(0.3)
	_dialog_box.append_text("Hikari: \"HEE!!!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"What should we do? What should we do?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"ARGGGHHHHHHHHHHHHHH-\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Angelo: \"SHUT UP ALREADY\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	# Angelo flew back (but why?)
	_flying_guardian._appearance.scale.x = 1
	_flying_guardian.play_animation("Fly")
	_anim_player.play("MeetAngelo8")
	yield(_anim_player, "animation_finished")
	_flying_guardian.play_animation("Stand")
	_little_girl.play_animation("Idle")
	_little_girl._appearance.scale.x = -1
	_dialog_box.append_text("Angelo: \"You guys human being are sure such a pain pain in the ass creature...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Angelo: \"BE GRATEFUL, HUMAN!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Because I, The Almighty Angelo, will take you there.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko and Hikari: \"!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"...You ungrateful being...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Angelo: \"WHERE'S YOUR GRATITUDE?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko and Hikari: \"Ah, YES, THANK YOU VERY MUCH!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Tsk, such a fool...\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Don't you dare to think that I'll do this just for a favor.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"I hate to waste my time for something useless.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"If you dare to do another useless peformance, I'll attack you again like before.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"But I WON'T MISS!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_player.shake_screen(0.3)
	_dialog_box.append_text("Angelo \"YOU GOT ME?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Hikari: \"YES SIR!?\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Angelo: \"Now stop wasting my time and hop in!\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko and Hikari: \"Yes sir.\"[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_little_girl.play_animation("Walk")
	_anim_player.play("MeetAngelo9")
	yield(_anim_player, "animation_finished")
	_dialog_box.append_text("Kyoko: (...I don't really need to do much this time, huh?)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (Well, except for stopping her from being shattered to pieces that one time... )[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	_dialog_box.append_text("Kyoko: (Damn, she grown fast...)[break]", 100)
	yield(_dialog_box, "break_ended")
	_dialog_box.hide_box()
	body.set_current_state("IDLE")
	_meet_angelo.queue_free()
