extends Npc

onready var _anim_player = $AnimationPlayer
onready var _world = get_parent()

var _found_first_note = false
var _droped_box_path = "res://Object/DroppedBox.tscn"


func chat(source_position, dialog_box):
	if not _found_first_note:
		dialog_box.append_text("???: *sob*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: ...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		.chat(source_position, dialog_box)
	else:
		set_npc_direction(source_position)
		dialog_box.append_text("???: *sob*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: ...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: ...that, that's my note...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: *grab the notes*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Aah, ...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: Where did you find it?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Umm, somewhere around the corner[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: *Happy loli noises*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: THANK YOU SO MUCH, uhhh...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: It's Kyoko. Nice to meet you[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("???: Kyoko. *sob* My name is Hikari. Nice too meet you *sob*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		_anim_player.play("Normal")
		dialog_box.append_text("Hikari: ...Big sis Kyoko, did you find any other notes?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Sorry, i only found that. What's that?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: My lyric notes. I need that for tomorrow's concert[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		_anim_player.play("Sad")
		dialog_box.append_text("Hikari: I, i was playing around with my friends, then i got lost in this place[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: I playe here before, so i want to see more[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: I, i was playing around with my friends, then i got lost in the middle of here[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: I saw lot of cool thing here, so i write it in my lyric notes[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Err, okay...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: Then, *sob* bad creature appeare *sob* and, and i ran away,,,[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: ...it's okay, it seems safe here[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: *sob*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: Kyoko, can you help me?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Eehhhh,,,[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: *sob*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: ...I mean, you know, i don't really know where are we, and,,,[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: *sob* ...Please...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: ....[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: (Geez, i hate this)[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: ...I'll do my best...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		_anim_player.play("Normal")
		dialog_box.append_text("Hikari: Thank you[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: Ah!?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: ...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: Here, for you[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: It's pretty cool, right?[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: Yeah, sure...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		_anim_player.play("Happy")
		dialog_box.append_text("Hikari: *smile*[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Hikari: Alright, let's go!!![break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		dialog_box.append_text("Kyoko: ...[break]", 100)
		yield(dialog_box, "break_ended")
		dialog_box.hide_box()
		.chat(source_position, dialog_box)
		_world.spawn_drop_item(get_global_position(), _droped_box_path)
		queue_free()


func set_found_first_note(value):
	_found_first_note = value
